name: Build Windows EXE

on:
  push:
    branches: [ main, develop ]

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path 'requirements.txt') {
            python -m pip install -r requirements.txt
          }
          python -m pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          # Build a single-file executable. Remove --console for GUI apps.
          pyinstaller --onefile --name taskonaut src/main.py

      - name: Prepare output
        run: |
          # Ensure output directory exists
          if (-not (Test-Path -Path 'out')) { New-Item -ItemType Directory -Path 'out' | Out-Null }

          if (Test-Path 'dist\taskonaut.exe') {
            Copy-Item -Path 'dist\taskonaut.exe' -Destination 'out\taskonaut.exe' -Force
          } else {
            Write-Error 'ERROR: dist\taskonaut.exe not found'
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: taskonaut-windows
          path: out/taskonaut.exe
